### ISSUE TITLE
@teodorgeorgiev can you give commit rights to @myrmoteras and @Daniel-Mietchen ? 

### ISSUE THREAD

**Issue by qgroom** [pensoft/BiCIKL#21]
@teodorgeorgiev can you give commit rights to @myrmoteras and @Daniel-Mietchen ? 
Thanks!

**Comment by qgroom** [comment]
Also, @mtrekels and @mdmtrv

**Comment by teodorgeorgiev** [comment]
done!

**Comment by Daniel-Mietchen** [comment]
@teodorgeorgiev I still do not have write access here.

**Comment by teodorgeorgiev** [comment]
@Daniel-Mietchen 
![image](https://user-images.githubusercontent.com/4538487/134134883-77ab4b30-60de-448e-a362-da3519ae759a.png)
