### ISSUE TITLE
Topic 3: Improve clustering by adding an identifier with the schema instcode:catnumber

### ISSUE THREAD

**Issue by jholetschek** [pensoft/BiCIKL#29]
For the clustering, a the triple ID (inst:coll:cat) is added as an identifier for records. In ENA, for several records the voucher ID is constructed just with instcode and catnumber (inst:cat), missing the collection code. Adding this pattern to the array of used IDs for a specimen would increase the chances of matching with an ENA record.

Datasets affected: https://www.gbif.org/dataset/d8cd16ba-bb74-4420-821e-083f2bac17c2
Example ENA record with inst:cat as identifiers: https://www.gbif.org/occurrence/3349806846
Related specimen: https://www.gbif.org/occurrence/3347309485

From https://www.insdc.org/documents/feature-table
specimen_voucher="[institution-code:[collection-code:]]specimen_id"

Currently (22 September 21) there are at least 518.274 voucherIDs for sequences in ENA based on such a schema which could benefit from this improvement.

**Comment by timrobertson100** [comment]
I ran a fix for this and it didn't capture many new relationships.

On exploration, I found that NON_CONFLICTING_DATE and NON_CONFLICTING_COORDINATES require one side to be non-NULL.

I will explore changing that to accommodate missing information on both sides.

**Comment by timrobertson100** [comment]
For the test set we have in the hackathon (non-observation data) addressing null handling, and this inst:catNum means that

Before: 
  115,174,986 relationships covering 19,140,426 records
After:
  143,123,066 relationships covering 25,233,891 records

For ENA this means:
  4,350,320 relationships from 678,574 records
  4,749,772 relationships from 1,033,068 records

For Plazi publishers this means:
  158,133 relationships from 34,657 records
  188,200 relationships from 36,897 records

**Comment by timrobertson100** [comment]
Fixed in main
