### ISSUE TITLE
What does BFH refer to?

### ISSUE THREAD

**Issue by qgroom** [pensoft/BiCIKL#7]
@myrmoteras in your hackathon topic 8 you refer to "BFH", what is this?

**Comment by myrmoteras** [comment]
Bfh = Berner Fachhochschule. Homeinstitution of Beat Estermann. Partner in our Swissfunded eBioDiv project
Cheers
Donat Agosti

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Quentin Groom ***@***.***>
Sent: Saturday, August 14, 2021 12:05:16 PM
To: pensoft/BiCIKL ***@***.***>
Cc: Donat Agosti ***@***.***>; Mention ***@***.***>
Subject: [pensoft/BiCIKL] What does BFH refer to? (#7)

EXTERNAL SENDER


@myrmoteras<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmyrmoteras&data=04%7C01%7C%7Ce4cc1a17d31d4cb3f19c08d95f0b0404%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637645323202662954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j6BAByPo51Ycg5agSJmJxqDIz8z7OWHjgfKD8ht%2FbDo%3D&reserved=0> in your hackathon topic 8 you refer to "BFH", what is this?

**Comment by qgroom** [comment]
Thanks!
